### ISSUE TITLE
Question about the splash screen

### ISSUE THREAD

**Issue by bilalahmedmirza** [UrAvgCode/Chooser#11]
Hello, i am a constant user of your app and i have a question related to the splash screen.
i see that you have not created a separate activity to create a splash screen just as i follow this practice but i also see that you have not used any extra theme or drawable to make your splash screen that you set your theme differently at the start and after setting the content view you change it but you did not follow that approach aswell.
i follow this approach and as a result of this my spash screen turns a bit dark, dim if you will but your method is perfect as the your made splash screen does not dim or darken a bit.
Can you share how you made your splash screen?
Thanks

**Comment by UrAvgCode** [comment]
Thanks for using the app :)

I didn’t create a custom splash screen explicitly, it’s just the app icon shown before the app starts. I’m not sure if the splash screen is auto-generated or just how Android handles apps without a custom splash screen.

Hope this clears things up. If your splash screen needs to be something other than the app icon, this approach likely won’t work for you.
