### ISSUE TITLE
Sounds when touching the screen

### ISSUE THREAD

**Issue by ToNIX-** [UrAvgCode/Chooser#2]
Hi!

First of all, I want to personally thank you for the wonderful app. I found it randomly this morning and it has instantly replaced all the different finger chooser I had installed. Since chwazi has been abandoned for quite a while, I kept looking for the perfect app and this is it, really.

It would be nice to add an option to play some sounds when touching the screen and when the player/team/order is being determined, a bit like chwazi is doing, which would give a clue about what's happening in the background. 

Once again, thank you for creating Chooser!

**Comment by UrAvgCode** [comment]
Thank you very much for the positive feedback, I really appreciate it. 
The app is inspired by Chwazi and similar apps, I just wanted to keep the user interface and settings very simple and I don't yet know how best to implement a toggle for the sound. However, it would certainly give the app more flair. On the other hand, turning down the handset volume and making the sounds not too disruptive would also be a good solution.
I'm adding sound to my to-do list.
thanks again for the feedback :)

**Comment by ToNIX-** [comment]
I totally understand what you mean, in its current state, the interface is clean and fully functional, there's absolutely no clutter and unnecessary button.

Maybe something like long pressing the mode button to access a way to toggle the sounds on/off could work?

**Comment by UrAvgCode** [comment]
I've released a pre-release version with some test sounds and the option to long press the mode button to toggle the sound on and off. Feel free to give me feedback or suggestions for free sounds that I could use instead of the current ones.

**Comment by ToNIX-** [comment]
That was quick I noticed that when a sound is currently playing and you add another finger on the screen, the sound for the new finger is not being played.

There's also no sound when selecting the groups in the group mode.

I'll search for free sounds you could use, maybe we can find something really nice.

**Comment by UrAvgCode** [comment]
I'll close this issue for now, the latest version should have fixed the parallel sound playback issue. I've got someone who knows more about sound to come up with new sounds, but it might take a while. Feel free to open a new issue if anything comes up.
