### ISSUE TITLE
Making turn order mode more usable

### ISSUE THREAD

**Issue by Terrance** [UrAvgCode/Chooser#5]
Giving this app a try having come from [Start Player](https://play.google.com/store/apps/details?id=eu.marcelnijman.startplayer), and it's a neat open-source alternative.  🙂

A few of the games I play require a full turn order, and whilst the "order" mode here works, with a higher number of players it's a bit hard to use as the numbers don't stick around for long, especially when your number might be obscured by someone else's hand.

In comparison, Start Player effectively combines the "order" and "choose one" modes, revealing all at once:

<img src="https://github.com/UrAvgCode/Chooser/assets/4025899/3d3a129c-79b2-4482-a471-6ba37404187b" width="300">

I think there's a slight UX improvement to be had by at least keeping the numbers on screen until hands are removed, and maybe displaying the numbers visible from multiple angles, using the ring around each finger or otherwise.

**Comment by UrAvgCode** [comment]
Thank you for trying my app and for the feedback. 
I tried out Start Player and found that it might give the whole thing a bit more "excitement" if not everyone is selected at the same time, but you're definitely right about the fact that it's quite difficult to tell who got which number, especially with a lot of players, and the selection process could also be made a little faster. I'll try to implement a better solution with your suggestions.
Thanks again for the feedback

**Comment by UrAvgCode** [comment]
I've released a pre-release version with some of your suggestions, it still needs polishing, but feel free to give me some feedback.

**Comment by Terrance** [comment]
Thanks for the quick turnaround!  It's definitely an improvement having the numbers stick around, though by being under your finger you still have to pay attention at the right time, either to the initial reveal, or in the few seconds between lifting your finger and it disappearing.

I might be overthinking it at this point (and I should probably wait until I can try it again at another games session), but I think what really made Start Player useful was the minimal explanation needed ("put your finger on the phone and hold it there") -- the first player is clearly highlighted when only one is needed, and for full turn orders everyone can see their number spinning around their finger when they do manage to glance at it.

With Chooser, I had to clarify to people that they need to watch for their number, and we inevitably had to do it a second time as two people weren't paying enough attention.  Having the numbers under the fingers is just a tiny bit more friction ("now lift your finger up and read your number before it goes away"), but from playing with it here, it probably sticks around long enough to not be a big issue.  🙂

**Comment by ToNIX-** [comment]
Why not have the same animation as when the single player is chosen (the whole screen switching to the color of the selected player and "zooming" on it's location) for each finger selected, one after the other? The floating text could be black and I'd keep the numbers showing under each finger. It might be worth a try!

**Comment by UrAvgCode** [comment]
Using the same animation as selecting a single player might be a bit too much I think. I'm just experimenting a bit with which animations might fit.

**Comment by UrAvgCode** [comment]
I'm closing this issue for now, the circles now flash more clearly, stay on the screen a little longer and the numbers should be easier to read. If anything comes up, feel free to give more feedback in the future.
